
name: Java CI with Maven  

on:  
  push:  

jobs:  
  maven_build:  
    runs-on: ubuntu-latest  

    steps:  
      - uses: actions/checkout@v3  

      - name: Set up JDK  
        uses: actions/setup-java@v3  
        with:  
          java-version: '11'  
          distribution: 'temurin'  
          cache: maven  

      - name: Build with Maven  
        run: mvn -B package --file pom.xml  

      - name: Trigger Jenkins Job  
        run: |
          crumb=$(curl -s -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
          http://172.31.44.177:8080/crumbIssuer/api/xml?xpath=concat\(//crumbRequestField,\":\",//crumb\))

          curl -X POST http://172.31.44.177:8080/job/tomcat-deploy/build \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
          -H "$crumb"name: Java CI with Maven  

